#!/bin/sh

intern="eDP-1"
extern="HDMI-2"

chosen=$(printf "󰶐  Disconnect\n󰍺  Extra\n󱒃  Duplicate" | rofi -dmenu -i)

case "$chosen" in
"󰶐  Disconnect") xrandr --output "$extern" --off --output "$intern" --auto && setxkbmap -option caps:swapescape && xset s on +dpms && nitrogen --restore ;;
"󰍺  Extra") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 --primary && xrandr --output "$intern" --auto --output "$extern" --left-of "$intern" && setxkbmap -option caps:swapescape && xset s off -dpms && nitrogen --restore ;;
"󱒃  Duplicate") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 && xrandr --output "$intern" --auto --output "$extern" --same-as "$intern" && setxkbmap -option caps:swapescape && xset s off -dpms ;;
esac
