#!/bin/sh

intern="eDP-1"
extern="HDMI-2"

case "$1" in
    "disconnect") xrandr --output "$extern" --off --output "$intern" --auto ;;
    "extra") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 --primary && xrandr --output "$intern" --auto --output "$extern" --left-of "$intern" && nitrogen --restore ;;
    "duplicate") xrandr --output "$extern" --set audio force-dvi --mode 1920x1080 && xrandr --output "$intern" --auto --output "$extern" --same-as "$intern" ;;
esac
